name: Go Actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt-get
        run: sudo apt-get update -y
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: tidy
        run: go mod tidy
      - name: install aws cli, pnpm
        run: sudo apt-get install awscli npm -y
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Build
        run: go build -v
      - name: Test
        run: go test -v ./...